[server]
headless = true

[theme]
primaryColor = "#4CAF50"

[browser]
serverAddress = "doctor-buddy.streamlit.app"
serverPort = 8501

[general]
page_image = "https://raw.githubusercontent.com/Riiocodee/doctor-buddy/main/images-thumbnail.jpg"




